stages:
  - triggers
  - deploy

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'ucdev/docker-deployer'
    file: 'templates/.docker-deploy.yml'

build-server:
  stage: triggers
  trigger:
    include:
      - local: server/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - server/**/*

build-client:
  stage: triggers
  trigger:
    include:
      - local: client/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - client/**/*

deploy:
  extends: .docker-deploy
  stage: deploy
  script:
    - echo $CI_DEPLOY_PASSWORD | docker login --username $CI_DEPLOY_USER --password-stdin $CI_REGISTRY
    - docker-compose --file docker-compose.yml config > interpolated-docker-compose.yml
    - docker stack deploy --compose-file interpolated-docker-compose.yml --with-registry-auth $APP_NAME
  variables:
    APP_NAME: $CI_PROJECT_NAME
    SERVER_IMAGE: $CI_REGISTRY_IMAGE/server:master
    CLIENT_IMAGE: $CI_REGISTRY_IMAGE/client:master
    APP_HOST: $PRODUCTION_DOMAIN
    NODE_ENV: "production"
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  only:
    - master
